### ISSUE TITLE
Wire and Reg Assignments

### ISSUE THREAD

**Issue by joaovam** [lac-dcc/chimera#12]
Some assignments can only be used with registers, for example, inside an always block. We need to differ when it is necessary to use reg and when it can be wire in the [type inference](https://github.com/lac-dcc/chimera/blob/main/src/TypeInference.cpp).

**Comment by luizademelo** [comment]
This table could be interesting to analyze assignments:
![Captura de tela 2024-08-28 145214](https://github.com/user-attachments/assets/db20e416-5e72-413a-bdd4-8dac03a43ac6)
