### ISSUE TITLE
Procedural Assignment to non-register

### ISSUE THREAD

**Issue by joaovam** [lac-dcc/chimera#22]
### Jasper output
- [ERROR (VERI-1100)] ./1_gram_verilog_file_495.v(20): procedural assignment to a non-register 'id_6' is not permitted

### Seed to reproduce
- 3060991799
- 1 gram

### Description
Procedural Assignments can only happen to variables and registers, we must make sure that during [type inference](https://github.com/lac-dcc/chimera/blob/main/src/TypeInference.cpp) these IDs are marked as REG. 

It usually happens with parameters, maybe we should add them to type inference.

**Comment by luizademelo** [comment]
Does that mean that "parameters" should always be treated as REG in type inference?
