### ISSUE TITLE
Non-net port cannot be of mode inout

### ISSUE THREAD

**Issue by joaovam** [lac-dcc/chimera#46]
```systemverilog
module module_2 (
    id_1
);
  inout id_1; <-
  logic id_1 = 1'b0;
  type_4(
      .id_0(id_2), .id_1(1 - 1'b0)
  ); 
module_1();
```

`Seed: 2537806191`

**Comment by luizademelo** [comment]
I think that the problem is because id_1 is declared again, but with logic type. For example, in this program:
```systemverilog
module module_0 (
    id_1,
    id_2,
    id_3,
    id_4,
    id_5,
    id_6,
    id_7,
    id_8,
    id_9,
    id_10,
    id_11,
    id_12,
    id_13,
    id_14
);
  inout id_14;
  inout id_13;
  inout id_12;
  input id_11;
  inout id_10;
  output id_9;
  output id_8;
  output id_7;
  output id_6;
  output id_5;
  input id_4;
  output id_3;
  inout id_2;
  inout id_1;
  logic id_14 = {1 && id_12.id_1[1 : 1][1'b0]};
endmodule
```
Jasper only complains about id_14

**Comment by joaovam** [comment]
Hi @luizademelo, That's correct, but, id_14 is not actually being declared again, the line `logic id_14` defines the id as logic, when we have no declaration of type the default option is wire, which is a net type. we need to find a way to forbid ports declared as inout to be a type that is not a net or the contrary, forbid non-net ports to be inout.
